
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const USER_LOADED_FAIL = "USER_LOADED_FAIL"
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const GET_ERRORS = "GET_ERRORS";
export const CREATE_MESSAGE = "CREATE_MESSAGE";

export const LOGGED_IN = 'woozee/auth/LOGGED_IN';
export const LOGGED_OUT = 'woozee/auth/LOGGED_OUT';
// 
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const VERIFY_SUCCESS = "VERIFY_SUCCESS";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const USER_IMAGE_SUCCESS = "USER_IMAGE_SUCCESS";
export const USER_IMAGE_BASE_URL_SUCCESS = "USER_IMAGE_BASE_URL_SUCCESS";
// 
export const USER_EMAIL_SUCCESS = "USER_EMAIL_SUCCESS";
export const CHANGE_USER_PASSWORD_SUCCESS = "CHANGE_USER_PASSWORD_SUCCESS";
export const GET_USERS = "GET_USERS";
export const UPDATE_PROFILE_LOADING = "UPDATE_PROFILE_LOADING"
export const UPDATE_PROFILE_DONE = "UPDATE_PROFILE_DONE"
export const UPDATE_USER_INFO = 'UPDATE_USER_INFO'
export const UPDATE_NAME = 'UPDATE_NAME';

//MERCHANT
export const GET_MERCHANTS = 'GET_MERCHANTS';
export const ADD_MERCHANT = 'ADD_MERCHANT';
export const MERCHANT_LOADING = 'MERCHANT_LOADING'
export const DELETE_POST = 'DELETE_POST';
export const GET_MERCHANT = 'GET_MERCHANT';

export const SELECTED_FLIGHT_OFFER = 'SELECTED_FLIGHT_OFFER'
export const SELECTED_FLIGHT_MERCHANT = 'SELECTED_FLIGHT_MERCHANT'
export const SELECTED_TICKET_OPTION = 'SELECTED_TICKET_OPTION'
export const PASSENGER_DETAIL = 'PASSENGER_DETAIL'
export const SELECTED_FLIGHT_INSURANCE = 'SELECTED_FLIGHT_INSURANCE'
export const INSURER_DETAIL = 'INSURER_DETAIL'

//FLIGHT SEARCH
export const FLIGHT_SEARCH_REQUEST = 'FLIGHT_SEARCH_REQUEST'
export const FLIGHT_SEARCH_SUCCESS = 'FLIGHT_SEARCH_SUCCESS'
export const FLIGHT_SEARCH_FAILURE = 'FLIGHT_SEARCH_FAILURE'
export const RESET_FLIGHT_DETAIL = 'RESET_FLIGHT_DETAIL'
export const LOADING = "LOADING"
export const FLIGHT_PAYMENT_REQUEST = 'FLIGHT_PAYMENT_REQUEST'
export const CONFIRM_FLIGHT_PAYMENT_REQUEST = 'CONFIRM_FLIGHT_PAYMENT_REQUEST'
export const CONFIRM_FLIGHT_PAYMENT_SUCCESS = 'CONFIRM_FLIGHT_PAYMENT_SUCCESS'
export const CONFIRM_FLIGHT_PAYMENT_FAILURE = 'CONFIRM_FLIGHT_PAYMENT_FAILURE'

//STEPPER
export const FLIGHT_STEPPER_INDEX = 'FLIGHT_STEPPER_INDEX'
export const INSURANCE_STEPPER_INDEX = 'INSURANCE_STEPPER_INDEX'
export const NAVIGATE_TO_INSURANCE_PREVIOUS = 'NAVIGATE_TO_INSURANCE_PREVIOUS'
export const NAVIGATE_TO_FLIGHT_PREVIOUS = 'NAVIGATE_TO_FLIGHT_PREVIOUS'

export const UPDATE_PASSENGER_COUNTER = 'UPDATE_PASSENGER_COUNTER'

//NOTIFICATION
export const NOTIFICATION = 'NOTIFICATION'
export const SUCCESS_DISPLAYED = "woozeee/notification/SUCCESS_DISPLAYED";
export const PROCESSING = "woozeee/notification/PROCESSING";
export const PROCESSED = "woozeee/notification/PROCESSED";
export const EMAIL_VERIFIED = "woozeee/notification/EMAIL_VERIFIED";
export const WARNING_DISPLAYED = "woozeee/notification/WARNING_DISPLAYED";
export const ERROR_DISPLAYED = "woozeee/notification/ERROR_DISPLAYED";
export const INFO_DISPLAYED = "woozeee/notification/INFO_DISPLAYED";
export const OFFLINE_ERROR_DISPLAYED = "woozeee/notification/OFFLINE_ERROR_DISPLAYED";
export const MESSAGE_CLEARED = "woozeee/notification/MESSAGE_CLEARED ";
export const TIME_OUT = 10000;
